### ISSUE TITLE
Module should not require DOM as a typescript compiler option

### ISSUE THREAD

**Issue by jeffreylanters** [aaronsky/appstoreconnect#2]
Your library requires the `dom` library as a compiler option when you're using your module in TypeScript. This is because you use the type `URL` in your typings. You might want to consider change this into `string`.

```
node_modules/appstoreconnect/dist/v1/routes/testflight/builds/types.d.ts:300:19
error TS2304: Cannot find name 'URL'. In templateUrl?: URL;
```

**Comment by aaronsky** [comment]
The URL type I'm using is from the `url` module in the Node.js stdlib. Are you trying to use this package in the browser?

**Comment by jeffreylanters** [comment]
No, I'm using it in the NodeJS environment. Typescript tells me to add the `dom` library to resolve this issue.

**Comment by aaronsky** [comment]
What version of Node are you using, and could you share me your tsconfig.json?
